algoritmo "Sei fazer conta (Não muitas)"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : [Samara Souza]
// Descrição   : dobro e o triplo do número digitado
// Autor(a)    : Vinicius Lozano De Oliveira - 04156102
// Data atual  : 09/MAR/2024
var
numero: inteiro

inicio
escreval("Me fale um número!")
leia(numero)
escreval("O dobro de ", numero, " é ", numero*2, " e o triplo ", numero*3)

fimalgoritmo