algoritmo "Conversor de moeda"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : [Samara Souza]
// Descrição   : Dolares para real
// Autor(a)    : Vinicius Lozano De Oliveira - 04156102
// Data atual  : 09/MAR/2024
var

di, d, r: real

inicio
escreval("Escreva o valor em Dolares da cotação do dia e o valor a ser trocado!")
leia(di,d) 
// d:10   di:5
r <- d * di
escreval("Agora você tem ", r, "R$" )

fimalgoritmo