algoritmo "Conversor de temperatura"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : [Samara Souza]
// Descrição   : Celsius para Fahrenheit 
// Autor(a)    : Vinicius Lozano De Oliveira - 04156102
// Data atual  : 09/MAR/2024
var

c, f: inteiro

inicio
escreval("Escreva o valor em Celsius: ")
leia(c) // fornecido: 30

f <- c*1.8 + 32

escreval("A quantidade em Fahrenheit é de: ", f )

fimalgoritmo