algoritmo "Media"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : [Samara Souza]
// Descrição   : Media de quatro numeros
// Autor(a)    : Vinicius Lozano De Oliveira - 04156102
// Data atual  : 09/MAR/2024
var

a, b, c, d, m: inteiro

inicio

escreval("Escreva quatro numeros: ")
leia(a,b,c,d) // a : 10, b: 8, c: 8, d: 10  

m <- (a + b + c + d) / 4

escreval("Sua média é de: ", m)
fimalgoritmo