algoritmo "perimetro do triângulo 03"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : [Samara Souza]
// Descrição   : perimetro do triangulo iisósceles
// Autor(a)    : Vinicius Lozano De Oliveira - 04156102
// Data atual  : 09/MAR/2024
var

a,b,c,p: inteiro

inicio
escreval("Escreva os lados do triangulo")
leia(a,b,c)
p <- a + b + c

escreval("o perimetro do triângulo é de: ", p )

fimalgoritmo