algoritmo "área do triângulo"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : [Samara Souza]
// Descrição   : Os professores leem isso aqui? como faz pra ler 130 diferentes.
// Autor(a)    : Vinicius Lozano De Oliveira - 04156102
// Data atual  : 09/MAR/2024
var

a, b, h: inteiro

inicio
escreval("Escreva a base e a altura do triângulo em Cm")
leia(b,h)

a <- b*h/2

escreval("A área do triangulo é de: ", a , "cm quadrados")

fimalgoritmo