algoritmo "Conversor de peso"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : [Samara Souza]
// Descrição   : Libras para quilo 
// Autor(a)    : Vinicius Lozano De Oliveira - 04156102
// Data atual  : 09/MAR/2024
var

l, k: real

inicio
escreval("Escreva o valor em Libras: ")
leia(l) 

k <- l / 2.2046

escreval("A quantidade em Quilos é de: ", k:4:2 )

fimalgoritmo